#!/bin/sh
#
# Copyright (C) Senorsen (Zhang Sen) <sen@senorsen.com>
#
# This software is distributed under the terms of GPLv3 or later,
# See `LICENSE' for more information. 
#

do_systemd_inst() {
	cp /usr/share/git-auto-pull/git-auto-pull.service /lib/systemd/system/git-auto-pull.service
	chown root:root /lib/systemd/system/git-auto-pull.service
	systemctl daemon-reload
	systemctl enable git-auto-pull.service
	[ -f /usr/sbin/policy-rc.d ] && /usr/sbin/policy-rc.d && systemctl restart git-auto-pull.service
    [ ! -f /usr/sbin/policy-rc.d ] && systemctl restart git-auto-pull.service
}

do_sysvinit_inst() {
	cp /usr/share/git-auto-pull/git-auto-pull /etc/init.d/git-auto-pull
	chmod 755 /etc/init.d/git-auto-pull
	chown root:root /etc/init.d/git-auto-pull
	update-rc.d git-auto-pull defaults 2>&1 >/dev/null || chkconfig git-auto-pull on || true
	[ -f /usr/sbin/policy-rc.d ] && /usr/sbin/policy-rc.d && service git-auto-pull restart
    [ ! -f /usr/sbin/policy-rc.d ] && service git-auto-pull restart
}

pidof systemd 2>&1 >/dev/null && do_systemd_inst || true
pidof systemd 2>&1 >/dev/null || do_sysvinit_inst || true

[ -f /usr/share/git-auto-pull/qsc.list ] && cp /usr/share/git-auto-pull/qsc.list /etc/apt/sources.list.d/qsc.list || true
[ -f /usr/share/git-auto-pull/qsc.public.key ] && {
	apt-key add /usr/share/git-auto-pull/qsc.public.key 2>&1 >/dev/null || true
} || true


